version: '3'

services:
  trading-bot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
