# Generated by Django 5.1.4 on 2025-05-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("timeframe", models.CharField(max_length=10)),
                ("recommendation", models.CharField(max_length=10)),
                ("patterns", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("rsi", models.FloatField()),
                ("macd", models.FloatField()),
                ("macd_signal", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
